# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CheckMoney' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CheckMoney
  pod 'GoogleSignIn'
  pod 'JJFloatingActionButton'
  pod 'SideMenu'
  pod 'Charts'
  pod 'BetterCodable', '~>0.1.0'
  pod 'Kingfisher', '~> 7.0'
end
